spring.application.name=document-flow-api
spring.datasource.url=jdbc:postgresql://localhost:5432/documentflow_db
spring.datasource.username=postgres
spring.datasource.password=2468
spring.jpa.hibernate.ddl-auto=update
spring.mail.host=localhost
spring.mail.port=1025
